
CREATE TABLE [dbo].[tblAgent](
	[AgentID] [bigint] IDENTITY(1,1) NOT NULL,
	[AgentCode] [varchar](12) NOT NULL,
	[Branch] [varchar](10) NULL,
	[FirstName] [varchar](150) NULL,
	[MiddleName] [varchar](50) NULL,
	[LastName] [varchar](50) NULL,
	[LicenseNo] [varchar](20) NULL,
	[LicenseIssueDate] [datetime] NULL,
	[LicenseExpiryDate] [datetime] NULL,
	[NomineeName] [varchar](150) NULL,
	[NomineeRelation] [varchar](20) NULL,
	[NomineeAddress] [varchar](100) NULL,
	[BankAcNo] [varchar](20) NULL,
	[BankCode] [varchar](5) NULL,
	[AccountNo] [bigint] NULL,
	[DeathDate] [datetime] NULL,
	[CauseOfDeath] [varchar](30) NULL,
	[CreatedBy] [varchar](50) NULL,
	[CreatedDate] [datetime] NULL,
	[IsActive] [bit] NULL,
	[ModifiedBy] [varchar](50) NULL,
	[ModifiedDate] [datetime] NULL,
	[TraineeId] [int] NULL,
	[BankBranch] [varchar](50) NULL,
	[PANNo] [varchar](20) NULL,
	[NepName] [nvarchar](150) NULL,
	[FatherName] [varchar](150) NULL,
	[GrandFatherName] [varchar](150) NULL,
	[WebSite] [varchar](150) NULL,
	[Address] [varchar](150) NULL,
	[NepAddress] [nvarchar](150) NULL,
	[PhoneNo] [varchar](150) NULL,
	[MobileNo1] [varchar](150) NULL,
	[MobileNo2] [varchar](150) NULL,
	[Email] [varchar](150) NULL,
	[TemporaryAddress] [varchar](150) NULL,
	[IsCorporate] [bit] NULL,
	[DOB] [datetime] NULL,
	[Occupation] [varchar](150) NULL,
	[Qualification] [varchar](150) NULL,
	[Parentcode] [varchar](10) NULL,
	[IsParentcode] [bit] NULL,
	[SequenceNo] [bigint] NULL,
	[StaffCode] [varchar](12) NULL,
	[OldAgentCode] [varchar](12) NULL,
	[IsOnline] [bit] NULL,
	[ForcePwd] [bit] NULL,
	[ResetToken] [varchar](100) NULL,
	[UserPwd] [varchar](400) NULL,
	[SonName] [varchar](250) NULL,
	[SpouseName] [varchar](250) NULL,
	[MotherName] [varchar](250) NULL,
	[DaughterName] [varchar](250) NULL,
	[DaughterInLaw] [varchar](250) NULL,
	[AgeProofDocIssueDate] [varchar](250) NULL,
	[FatherInLawName] [varchar](250) NULL,
	[IsPoliticallyInvolved] [varchar](250) NULL,
	[IsAmlCrime] [varchar](250) NULL,
	[IDIssueDate] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[AgentCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblInsuredDetail]    Script Date: 11/25/2025 2:07:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblInsuredDetail](
	[RowId] [bigint] IDENTITY(1,1) NOT NULL,
	[RegisterNo] [bigint] NOT NULL,
	[ClientNo] [varchar](255) NULL,
	[Branch] [smallint] NULL,
	[FirstName] [varchar](45) NULL,
	[MiddleName] [varchar](45) NULL,
	[LastName] [varchar](45) NULL,
	[ProvinceID] [nvarchar](50) NULL,
	[DistrictID] [nvarchar](50) NULL,
	[MunicipalityID] [nvarchar](50) NULL,
	[EngStreetName] [varchar](255) NULL,
	[NepName] [nvarchar](80) NULL,
	[NepStreetName] [nvarchar](100) NULL,
	[EngFatherName] [varchar](255) NULL,
	[NepFatherName] [nvarchar](80) NULL,
	[NomineeName] [varchar](255) NULL,
	[EngNomineeAddress] [varchar](255) NULL,
	[NomRelation] [varchar](255) NULL,
	[NepNomineeName] [nvarchar](80) NULL,
	[NepNomineeAddress] [nvarchar](100) NULL,
	[EngNomineeFatherName] [varchar](255) NULL,
	[NepNomineeFatherName] [nvarchar](70) NULL,
	[DOB] [date] NULL,
	[Age] [smallint] NULL,
	[Qualification] [smallint] NULL,
	[Sex] [char](4) NULL,
	[Nationality] [smallint] NULL,
	[Profession] [smallint] NULL,
	[PBox] [varchar](255) NULL,
	[Email] [varchar](255) NULL,
	[Phone] [varchar](255) NULL,
	[Fax] [varchar](255) NULL,
	[Mobile] [varchar](255) NULL,
	[CreatedBy] [varchar](255) NULL,
	[CreatedDate] [datetime] NULL,
	[IsActive] [bit] NULL,
	[AgeProofDocType] [int] NULL,
	[AgeProofDocNo] [varchar](255) NULL,
	[AgeProofDocIssueDate] [date] NULL,
	[AgeProofDocIssueDistrictID] [varchar](255) NULL,
	[PolicyNo] [varchar](255) NULL,
	[TempAddress] [nvarchar](max) NULL,
	[TempDistrict] [nvarchar](max) NULL,
	[BranchRemarks] [varchar](255) NULL,
	[WardNo] [nvarchar](50) NULL,
	[Occupation2] [varchar](255) NULL,
	[AutoLoan] [varchar](255) NULL,
	[PanNo] [varchar](255) NULL,
	[Salutation] [varchar](10) NULL,
	[FNameSoundex]  AS (soundex([FirstName])),
	[MNameSoundex]  AS (soundex([MiddleName])),
	[LNameSoundex]  AS (soundex([LastName])),
	[IsForeignEmployee] [bit] NULL,
	[FECountry] [varchar](255) NULL,
	[StaffCode] [varchar](255) NULL,
	[subbranch] [varchar](255) NULL,
	[SpouseAge] [int] NULL,
	[SpouseName] [varchar](255) NULL,
	[NepSpouseName] [nvarchar](100) NULL,
	[SpouseDOB] [date] NULL,
	[SpouseAddress] [varchar](255) NULL,
	[NepSpouseAddress] [nvarchar](100) NULL,
	[SpouseProfession] [varchar](255) NULL,
	[NomineePhoneNo] [bigint] NULL,
	[CorpAgentBrnch] [varchar](255) NULL,
	[OldRegisterno] [bigint] NULL,
	[NomineeDistrict] [nvarchar](100) NULL,
	[NomineeWardNo] [nvarchar](100) NULL,
	[ForcePwd] [bit] NULL,
	[UserPwd] [varchar](255) NULL,
	[IsOnline] [bit] NULL,
	[ResetToken] [varchar](255) NULL,
	[DATASOURCE] [varchar](255) NULL,
	[ModifiedBY] [varchar](255) NULL,
	[ModifiedDate] [datetime] NULL,
	[IncomeAmt] [money] NULL,
	[IncomeMode] [varchar](255) NULL,
	[FirmName] [varchar](255) NULL,
	[ProposerFirstName] [varchar](255) NULL,
	[ProposerMiddleName] [varchar](255) NULL,
	[ProposerLastName] [varchar](255) NULL,
	[ProposerNepName] [varchar](255) NULL,
	[ProposerSex] [varchar](255) NULL,
	[ProposerNationality] [varchar](255) NULL,
	[ProposerDOB] [datetime] NULL,
	[ProposerProvinceID] [varchar](255) NULL,
	[ProposerDistrictID] [varchar](255) NULL,
	[ProposerQualification] [varchar](255) NULL,
	[ProposerEngStreetName] [varchar](255) NULL,
	[ProposerProfession] [varchar](255) NULL,
	[ProposerNomRelation] [varchar](255) NULL,
	[ProposerEngFatherName] [varchar](255) NULL,
	[ProposerNepFatherName] [varchar](255) NULL,
	[EndorsementType] [varchar](255) NULL,
	[ProposerWardNo] [varchar](255) NULL,
	[AgentCode] [varchar](255) NULL,
	[TransferPolicyNo] [varchar](max) NULL,
	[EmployeeID] [varchar](max) NULL,
	[NewClientId] [varchar](250) NULL,
	[BankName] [varchar](500) NULL,
	[BankCode] [varchar](25) NULL,
	[BankBranch] [varchar](25) NULL,
	[BankAccountNo] [varchar](25) NULL,
	[AccountHolderName] [varchar](50) NULL,
	[EngMotherName] [varchar](50) NULL,
	[NepMotherName] [nvarchar](50) NULL,
	[EngGrandFatherName] [varchar](50) NULL,
	[NepGrandFatherName] [nvarchar](50) NULL,
	[IncomeSource] [varchar](30) NULL,
	[RiskCriteria] [varchar](100) NULL,
	[RiskCategory] [varchar](100) NULL,
	[IsUnsanctioned] [bit] NULL,
	[PreviousSAProposer] [money] NULL,
	[IsAdvancePayment] [bit] NULL,
	[GroupStampCharge] [money] NULL,
 CONSTRAINT [PK__tblInsur__B921EA290243CFE9] PRIMARY KEY CLUSTERED 
(
	[RegisterNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblInsuredUnderwriting]    Script Date: 11/25/2025 2:07:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblInsuredUnderwriting](
	[RowId] [bigint] IDENTITY(1,1) NOT NULL,
	[RegisterNo] [bigint] NOT NULL,
	[RegisterDate] [datetime] NULL,
	[PlanID] [smallint] NULL,
	[Term] [smallint] NULL,
	[SA] [money] NULL,
	[Premium] [money] NULL,
	[BasicPremium] [money] NULL,
	[TableRate] [float] NULL,
	[ExtraPremium] [money] NULL,
	[ExtraPremiumRemarks] [varchar](25) NULL,
	[TotalRiderPremium] [money] NULL,
	[PayMode] [char](4) NULL,
	[IncomeAmt] [money] NULL,
	[IncomeMode] [char](4) NULL,
	[AgentCode] [varchar](12) NULL,
	[ReinsuredSA] [money] NULL,
	[MedicalExaminationFee] [money] NULL,
	[PolicyNo] [varchar](50) NULL,
	[DiscountAmount] [money] NULL,
	[DiscountPercent] [float] NULL,
	[OverloadAmount] [money] NULL,
	[OverloadPercent] [float] NULL,
	[HealthExtraAmount] [money] NULL,
	[OccExtraAmount] [money] NULL,
	[NonStdAgeExtraAmount] [money] NULL,
	[ServiceCharge] [money] NULL,
	[DoJoinForce] [bit] NULL,
	[DoMigrate] [bit] NULL,
	[DoRiskyJob] [bit] NULL,
	[DOC] [datetime] NULL,
	[ApprovedDate] [datetime] NULL,
	[ApprovedRemarks] [varchar](255) NULL,
	[SalesUnit] [varchar](20) NULL,
	[IsApproved] [bit] NULL,
	[ApprovedBy] [varchar](50) NULL,
	[IsEditable] [bit] NULL,
	[IsPregnent] [bit] NULL,
	[FirmName] [varchar](100) NULL,
	[PayingTerm] [smallint] NULL,
	[SADiscountPercent] [float] NULL,
	[SAOverloadPercent] [float] NULL,
	[ExtraDiscount] [money] NULL,
	[ExtraDiscountRemarks] [varchar](50) NULL,
	[IsPolicyIssued] [bit] NULL,
	[ADBRiderId] [int] NULL,
	[OccupationExtraAmount] [money] NULL,
	[HealthExtraAmounts] [money] NULL,
	[NonStdAgeExtraAmounts] [money] NULL,
	[DHealthExtraId] [int] NULL,
	[DHealthExtra] [int] NULL,
	[FinalRate] [money] NULL,
	[BasicPremiumBeforePaymodeDiscount] [money] NULL,
	[BasicPremiumAfterPaymodeDiscount] [money] NULL,
	[DeclineRemarks] [varchar](100) NULL,
	[CancelRemarks] [varchar](100) NULL,
	[PostponeDate] [datetime] NULL,
	[PolicyStatus] [varchar](100) NULL,
	[Cancel] [varchar](10) NULL,
	[PostponeRemarks] [varchar](100) NULL,
	[occextraid] [int] NULL,
	[ExtraRiders] [money] NULL,
	[ExtraRidersRemarks] [varchar](max) NULL,
	[StaffCode] [varchar](100) NULL,
	[GroupCode] [varchar](100) NULL,
	[ModifiedBy] [varchar](100) NULL,
	[ModifiedDate] [date] NULL,
	[CorpDiscount] [money] NULL,
	[ExtraRating] [money] NULL,
	[IsLoanPolicy] [varchar](100) NULL,
	[CompanyCode] [varchar](100) NULL,
	[UnApprovedBy] [varchar](20) NULL,
	[PreviousSA] [money] NULL,
	[IsCompanyPolicy] [varchar](100) NULL,
	[NonLoanPolicyCode] [varchar](max) NULL,
	[OldPlanId] [varchar](10) NULL,
	[TransferDOC] [date] NULL,
	[TransferFUP] [date] NULL,
	[TransferInstalment] [bigint] NULL,
	[NewClientId] [varchar](250) NULL,
	[IsUnsanctioned] [bit] NULL,
	[DirectDiscount] [money] NULL,
	[PreviousSAProposer] [money] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblKycClientId]    Script Date: 11/25/2025 2:07:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblKycClientId](
	[RowId] [int] IDENTITY(1,1) NOT NULL,
	[NewClientId] [varchar](50) NULL,
	[ClientNo] [varchar](50) NULL,
	[KycId] [varchar](50) NULL,
	[PolicyNo] [varchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblKYCDetails]    Script Date: 11/25/2025 2:07:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblKYCDetails](
	[RowId] [bigint] IDENTITY(1,1) NOT NULL,
	[ClientNo] [varchar](255) NULL,
	[Branch] [smallint] NOT NULL,
	[Salutation] [varchar](50) NULL,
	[FirstName] [varchar](45) NOT NULL,
	[MiddleName] [varchar](45) NULL,
	[LastName] [varchar](45) NOT NULL,
	[DOB] [date] NOT NULL,
	[Age] [smallint] NULL,
	[Sex] [varchar](3) NULL,
	[ProposerName] [nvarchar](100) NULL,
	[ProvinceID] [nvarchar](50) NULL,
	[DistrictID] [nvarchar](50) NULL,
	[MunicipalityID] [nvarchar](50) NULL,
	[EngStreetName] [varchar](100) NULL,
	[NepName] [nvarchar](80) NULL,
	[NepStreetName] [nvarchar](100) NULL,
	[EngFatherName] [varchar](45) NULL,
	[NepFatherName] [nvarchar](80) NULL,
	[PBox] [varchar](11) NULL,
	[Email] [varchar](30) NULL,
	[Phone] [varchar](22) NULL,
	[Fax] [varchar](22) NULL,
	[Mobile] [varchar](70) NOT NULL,
	[CreatedBy] [varchar](50) NOT NULL,
	[CreatedDate] [datetime] NULL,
	[IsActive] [bit] NULL,
	[AgeProofDocType] [int] NULL,
	[AgeProofDocNo] [varchar](30) NULL,
	[AgeProofDocIssueDate] [date] NULL,
	[AgeProofDocIssueDistrictID] [varchar](50) NULL,
	[TempAddress] [varchar](200) NULL,
	[TempDistrict] [varchar](200) NULL,
	[BranchRemarks] [varchar](255) NULL,
	[WardNo] [nvarchar](50) NULL,
	[HouseNo] [varchar](20) NULL,
	[Occupation2] [varchar](50) NULL,
	[Qualification] [smallint] NULL,
	[Profession] [smallint] NULL,
	[PanNo] [varchar](9) NULL,
	[FirmName] [varchar](500) NULL,
	[FirmAddress] [varchar](500) NULL,
	[IncomeAmt] [money] NULL,
	[BankAcNo] [varchar](100) NULL,
	[BankName] [varchar](100) NULL,
	[SpouseName] [varchar](150) NULL,
	[NepSpouseName] [nvarchar](150) NULL,
	[SpouseAddress] [varchar](150) NULL,
	[EngMotherName] [varchar](150) NULL,
	[GrandFatherName] [varchar](150) NULL,
	[SonName] [varchar](150) NULL,
	[DaughterName] [varchar](150) NULL,
	[DaughterInLawName] [varchar](150) NULL,
	[FatherInLawName] [varchar](150) NULL,
	[BirthPlace] [varchar](500) NULL,
	[Religion] [varchar](50) NULL,
	[Nationality] [varchar](50) NULL,
	[Gender] [varchar](50) NULL,
	[IncomeMode] [varchar](50) NULL,
	[IsOnline] [bigint] NULL,
	[NewClientId] [varchar](250) NULL,
	[IsNew] [varchar](5) NULL,
	[RiskCategory] [varchar](50) NULL,
	[IsPoliticallyInvolved] [varchar](50) NULL,
	[IsAmlCrime] [varchar](50) NULL,
	[ModifiedBy] [varchar](120) NULL,
	[ModifiedDate] [datetime] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblPolicyDetail]    Script Date: 11/25/2025 2:07:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblPolicyDetail](
	[RowId] [bigint] IDENTITY(1,1) NOT NULL,
	[RegisterNo] [bigint] NOT NULL,
	[PolicyNo] [varchar](50) NOT NULL,
	[Branch] [varchar](10) NULL,
	[ClientNo] [varchar](10) NULL,
	[RegisterDate] [datetime] NULL,
	[PlanID] [smallint] NULL,
	[Term] [smallint] NOT NULL,
	[SA] [decimal](10, 2) NULL,
	[Premium] [decimal](10, 2) NULL,
	[BasicPremium] [decimal](10, 2) NULL,
	[TableRate] [float] NULL,
	[HealthExtraAmount] [decimal](10, 2) NULL,
	[OccExtraAmount] [decimal](10, 2) NULL,
	[NonStdAgeExtraAmount] [decimal](10, 2) NULL,
	[ExtraPremium] [decimal](10, 2) NULL,
	[ExtraPremiumRemarks] [varchar](25) NULL,
	[TotalRiderPremium] [money] NULL,
	[PayMode] [char](4) NULL,
	[IncomeAmt] [decimal](20, 2) NULL,
	[IncomeMode] [char](4) NULL,
	[AgentCode] [varchar](12) NULL,
	[ReinsuredSA] [decimal](10, 2) NULL,
	[MedicalExaminationFee] [decimal](10, 2) NULL,
	[DiscountAmount] [decimal](10, 2) NULL,
	[DiscountPercent] [float] NULL,
	[OverloadAmount] [decimal](10, 2) NULL,
	[OverloadPercent] [float] NULL,
	[ServiceCharge] [decimal](10, 2) NULL,
	[DOC] [datetime] NULL,
	[FUP] [datetime] NULL,
	[MaturityDate] [datetime] NULL,
	[VestingDate] [datetime] NULL,
	[DefermentDate] [datetime] NULL,
	[RiskStartDate] [datetime] NULL,
	[CurrentStatus] [char](1) NULL,
	[PolicyLapsedDate] [datetime] NULL,
	[PolicyRevivedDate] [datetime] NULL,
	[RemarksOnExtraPremium] [varchar](25) NULL,
	[TotalLateFineAmount] [decimal](10, 2) NULL,
	[DifferencePrem] [decimal](10, 2) NULL,
	[DifferencePremiumReason] [varchar](255) NULL,
	[ExitType] [char](1) NULL,
	[ExitDate] [datetime] NULL,
	[SalesUnit] [varchar](20) NULL,
	[IsEditable] [char](1) NULL,
	[FPIPaidDate] [datetime] NULL,
	[InitialPremium] [decimal](10, 2) NULL,
	[TotalPremiumPaid] [money] NULL,
	[LateFineAmount] [decimal](10, 2) NULL,
	[AssigneeName] [varchar](50) NULL,
	[AssigneeAddress] [varchar](300) NULL,
	[FinalPremiumPayingDate] [datetime] NULL,
	[PayingTerm] [smallint] NOT NULL,
	[Age] [smallint] NULL,
	[ExtraDiscount] [decimal](10, 2) NULL,
	[ExtraDiscountRemarks] [varchar](50) NULL,
	[Instalment] [smallint] NULL,
	[CreatedBy] [varchar](30) NULL,
	[RiderNo] [varchar](20) NULL,
	[BankName] [nvarchar](200) NULL,
	[ChequeDate] [datetime] NULL,
	[PayHolderName] [nvarchar](200) NULL,
	[PayHolderAddress] [nvarchar](200) NULL,
	[ChequeNo] [nvarchar](50) NULL,
	[TerminationDate] [datetime] NULL,
	[isAML] [bit] NULL,
	[ReportGenerated] [datetime] NULL,
	[UniqueNumber] [nvarchar](100) NULL,
	[OldRegisterno] [bigint] NULL,
	[Finalprint] [varchar](10) NULL,
	[ClaimStatus] [varchar](20) NULL,
	[OldAgentCode] [varchar](500) NULL,
	[PreviousPolicy] [varchar](100) NULL,
	[NewClientId] [varchar](250) NULL,
	[CommissionDiscountAmount] [money] NULL,
	[TotalDiscountAmount] [money] NULL,
	[ApproveByUser] [varchar](100) NULL,
	[IsRebateTaken] [bit] NULL,
 CONSTRAINT [PK__tblPolic__2E13219723E84BC5] PRIMARY KEY CLUSTERED 
(
	[PolicyNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tblAgent] ADD  DEFAULT (getdate()) FOR [CreatedDate]
GO
ALTER TABLE [dbo].[tblInsuredDetail] ADD  CONSTRAINT [DF__tblInsure__Creat__1FEDB87C]  DEFAULT (getdate()) FOR [CreatedDate]
GO
ALTER TABLE [dbo].[tblInsuredDetail] ADD  DEFAULT ((1)) FOR [ForcePwd]
GO
ALTER TABLE [dbo].[tblInsuredDetail] ADD  DEFAULT ((0)) FOR [IsOnline]
GO
ALTER TABLE [dbo].[tblInsuredUnderwriting] ADD  DEFAULT ((0)) FOR [IsPolicyIssued]
GO
ALTER TABLE [dbo].[tblKYCDetails] ADD  DEFAULT (getdate()) FOR [CreatedDate]
GO
ALTER TABLE [dbo].[tblInsuredUnderwriting]  WITH NOCHECK ADD  CONSTRAINT [Fk_tblInsuredUnderwriting_RegisterNo] FOREIGN KEY([RegisterNo])
REFERENCES [dbo].[tblInsuredDetail] ([RegisterNo])
GO
ALTER TABLE [dbo].[tblInsuredUnderwriting] CHECK CONSTRAINT [Fk_tblInsuredUnderwriting_RegisterNo]
GO
ALTER TABLE [dbo].[tblPolicyDetail]  WITH NOCHECK ADD  CONSTRAINT [Fk_[tblPolicyDetail_RegisterNo] FOREIGN KEY([RegisterNo])
REFERENCES [dbo].[tblInsuredDetail] ([RegisterNo])
GO
ALTER TABLE [dbo].[tblPolicyDetail] CHECK CONSTRAINT [Fk_[tblPolicyDetail_RegisterNo]
GO
ALTER TABLE [dbo].[tblPolicyDetail]  WITH CHECK ADD  CONSTRAINT [Fk_tblpolicydetail_Branch] FOREIGN KEY([Branch])
REFERENCES [dbo].[tblBranch] ([Branch])
GO
ALTER TABLE [dbo].[tblPolicyDetail] CHECK CONSTRAINT [Fk_tblpolicydetail_Branch]
GO
