# Generated by Django 5.2.8 on 2025-11-17 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_code', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('citizenship_no', models.CharField(max_length=50, unique=True)),
                ('nid_no', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.DateField()),
                ('address', models.TextField(blank=True)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('kyc_updated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_no', models.CharField(max_length=50, unique=True)),
                ('sum_assured', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('term_years', models.PositiveIntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='kycform.customer')),
            ],
        ),
        migrations.CreateModel(
            name='PremiumPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='kycform.policy')),
            ],
        ),
    ]
