# Generated by Django 5.2.8 on 2025-11-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KycAgentInfo',
            fields=[
                ('agent_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'kyc_agent_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KycPolicy',
            fields=[
                ('policy_number', models.CharField(db_column='policy_number', max_length=50, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_column='user_id', max_length=50)),
                ('created_at', models.DateField(db_column='created_at')),
            ],
            options={
                'db_table': 'kyc_policy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KycUserInfo',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('dob', models.DateField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('user_email', models.CharField(blank=True, max_length=200, null=True)),
                ('citizenship_number', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('kyc_status', models.CharField(choices=[('NOT_INITIATED', 'Not Initiated'), ('PENDING', 'Pending'), ('INCOMPLETE', 'Incomplete'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='NOT_INITIATED', max_length=20)),
            ],
        ),
    ]
