# Generated by Django 5.2.8 on 2025-12-26 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycform', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KycMobileOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(help_text='10-digit Nepali mobile number', max_length=10)),
                ('otp_hash', models.CharField(help_text='SHA256 hash of OTP', max_length=64)),
                ('expires_at', models.DateTimeField(help_text='OTP expiry timestamp (2 minutes)')),
                ('attempts', models.PositiveSmallIntegerField(default=0, help_text='Number of failed verification attempts')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether OTP was successfully verified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kyc_mobile_otp',
                'indexes': [models.Index(fields=['user', 'mobile'], name='kyc_mobile__user_id_665863_idx'), models.Index(fields=['expires_at'], name='kyc_mobile__expires_f49678_idx')],
            },
        ),
    ]
