# Generated by Django 5.2.8 on 2025-12-26 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycform', '0002_kycmobileotp'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='kycmobileotp',
            name='kyc_mobile__user_id_665863_idx',
        ),
        migrations.RemoveIndex(
            model_name='kycmobileotp',
            name='kyc_mobile__expires_f49678_idx',
        ),
        migrations.RemoveField(
            model_name='kycmobileotp',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='kycmobileotp',
            name='user',
        ),
        migrations.AddField(
            model_name='kycmobileotp',
            name='kyc_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='mobile_otps', to='kycform.kycuserinfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kycmobileotp',
            name='expires_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='kycmobileotp',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kycmobileotp',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='kycmobileotp',
            name='otp_hash',
            field=models.CharField(max_length=128),
        ),
        migrations.AddIndex(
            model_name='kycmobileotp',
            index=models.Index(fields=['kyc_user', 'mobile'], name='kycform_kyc_kyc_use_2f4ffb_idx'),
        ),
        migrations.AlterModelTable(
            name='kycmobileotp',
            table=None,
        ),
    ]
