# Generated by Django 5.2.8 on 2025-11-20 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kycform', '0002_kycagentinfo_kycpolicy_kycuserinfo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kycuserinfo',
            table='kyc_user_info',
        ),
    ]
