# Generated by Django 5.2.8 on 2025-11-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycform', '0003_alter_kycuserinfo_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='KycAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
