# Generated by Django 5.2.8 on 2025-12-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycform', '0003_remove_kycmobileotp_kyc_mobile__user_id_665863_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycuserinfo',
            name='mobile_verified',
            field=models.BooleanField(default=False),
        ),
    ]
