# Generated by Django 5.2.8 on 2025-12-29 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycform', '0004_kycuserinfo_mobile_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyctemporary',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='kyc_temp', to='kycform.kycuserinfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kyctemporary',
            name='policy_no',
            field=models.CharField(max_length=30),
        ),
    ]
