# Generated by Django 5.2.8 on 2025-11-26 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kycform', '0004_kycadmin'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='kycuserinfo',
        #     name='user_email',
        # ),
    ]
