# Generated by Django 5.2.8 on 2025-11-26 06:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycform', '0004_kycadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='KycDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('PHOTO', 'Photo'), ('CITIZENSHIP_FRONT', 'Citizenship Front'), ('CITIZENSHIP_BACK', 'Citizenship Back'), ('NID', 'National Identity Card'), ('SIGNATURE', 'Signature'), ('ADDITIONAL', 'Additional Document')], max_length=50)),
                ('file_path', models.FileField(upload_to='kyc_docs/')),
                ('file_name', models.CharField(blank=True, max_length=150, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'kyc_documents',
            },
        ),
        migrations.CreateModel(
            name='KycSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=50)),
                ('marital_status', models.CharField(max_length=20)),
                ('spouse_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('grand_father_name', models.CharField(max_length=100)),
                ('father_in_law_name', models.CharField(blank=True, max_length=100, null=True)),
                ('son_name', models.CharField(blank=True, max_length=100, null=True)),
                ('daughter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('daughter_in_law_name', models.CharField(blank=True, max_length=100, null=True)),
                ('citizenship_no', models.CharField(max_length=100)),
                ('citizenship_issued_date_bs', models.CharField(max_length=20)),
                ('citizenship_issued_date_ad', models.DateField()),
                ('citizenship_issued_place', models.CharField(max_length=100)),
                ('passport_no', models.CharField(blank=True, max_length=50, null=True)),
                ('nid_no', models.CharField(blank=True, max_length=50, null=True)),
                ('perm_province', models.CharField(max_length=50)),
                ('perm_district', models.CharField(max_length=50)),
                ('perm_municipality', models.CharField(max_length=50)),
                ('perm_ward', models.IntegerField()),
                ('perm_address', models.CharField(max_length=100)),
                ('perm_house_number', models.CharField(blank=True, max_length=50, null=True)),
                ('temp_province', models.CharField(max_length=50)),
                ('temp_district', models.CharField(max_length=50)),
                ('temp_municipality', models.CharField(max_length=50)),
                ('temp_ward', models.IntegerField()),
                ('temp_address', models.CharField(max_length=100)),
                ('temp_house_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_branch', models.CharField(max_length=100)),
                ('bank_account_number', models.CharField(max_length=50)),
                ('bank_account_type', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=100)),
                ('occupation_description', models.CharField(blank=True, max_length=150, null=True)),
                ('income_mode', models.CharField(max_length=20)),
                ('annual_income', models.BigIntegerField()),
                ('income_source', models.CharField(max_length=100)),
                ('pan_number', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('employer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('office_address', models.CharField(blank=True, max_length=100, null=True)),
                ('nominee_name', models.CharField(max_length=100)),
                ('nominee_relation', models.CharField(max_length=50)),
                ('nominee_dob_bs', models.CharField(max_length=20)),
                ('nominee_dob_ad', models.DateField()),
                ('nominee_contact', models.CharField(max_length=20)),
                ('guardian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_relation', models.CharField(blank=True, max_length=100, null=True)),
                ('is_pep', models.BooleanField(default=False)),
                ('is_aml', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'kyc_submission',
            },
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='premiumpayment',
            name='policy',
        ),
        migrations.RemoveField(
            model_name='kycuserinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='kycuserinfo',
            name='citizenship_number',
        ),
        migrations.RemoveField(
            model_name='kycuserinfo',
            name='user_email',
        ),
        migrations.AddField(
            model_name='kycuserinfo',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='kycuserinfo',
            name='full_name_nep',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='kycuserinfo',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='kycadmin',
            table='kycform_kycadmin',
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='kycform.kycuserinfo'),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='kycform.kycuserinfo'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Policy',
        ),
        migrations.DeleteModel(
            name='PremiumPayment',
        ),
    ]
