# Generated by Django 5.2.8 on 2025-11-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycform', '0005_remove_kycuserinfo_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycuserinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='kycuserinfo',
            name='citizenship_number',
        ),
        migrations.AddField(
            model_name='kycuserinfo',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='kycuserinfo',
            name='full_name_nep',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='kycuserinfo',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
