# Generated by Django 5.2.8 on 2026-02-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycform', '0005_kyctemporary_user_alter_kyctemporary_policy_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Group',
                'ordering': ['group_id'],
                'managed': False,
            },
        ),
    ]
