# Generated by Django 5.2.8 on 2025-11-27 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kycform', '0005_kycdocument_kycsubmission_delete_agent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kycsubmission',
            old_name='citizenship_issued_date_ad',
            new_name='citizen_ad',
        ),
        migrations.RenameField(
            model_name='kycsubmission',
            old_name='citizenship_issued_date_bs',
            new_name='citizen_bs',
        ),
    ]
