# Generated by Django 5.2.8 on 2025-11-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycform', '0006_rename_citizenship_issued_date_ad_kycsubmission_citizen_ad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCTemporary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_no', models.CharField(max_length=30, unique=True)),
                ('data_json', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
