# Generated by Django 5.2.8 on 2025-11-30 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycform', '0007_kyctemporary'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycsubmission',
            name='additional_docs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='citizenship_back',
            field=models.FileField(blank=True, null=True, upload_to='kyc_docs/citizenship_back/'),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='citizenship_front',
            field=models.FileField(blank=True, null=True, upload_to='kyc_docs/citizenship_front/'),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='data_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='passport_doc',
            field=models.FileField(blank=True, null=True, upload_to='kyc_docs/passport/'),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='kyc_docs/photo/'),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='review_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='reviewed_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='kyc_docs/signature/'),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('INCOMPLETE', 'Incomplete'), ('REJECTED', 'Rejected'), ('VERIFIED', 'Verified')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_submission', to='kycform.kycuserinfo'),
        ),
    ]
