# Generated by Django 5.2.8 on 2025-11-30 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycform', '0008_kycsubmission_additional_docs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycsubmission',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='kycsubmission',
            name='bank_account_type',
        ),
        migrations.RemoveField(
            model_name='kycsubmission',
            name='citizenship_issued_place',
        ),
        migrations.RemoveField(
            model_name='kycsubmission',
            name='marital_status',
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='account_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='citizenship_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='dob_ad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='dob_bs',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='full_name_nep',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='annual_income',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='citizen_ad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='citizen_bs',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='citizenship_back',
            field=models.FileField(blank=True, null=True, upload_to='kyc/citizenship/'),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='citizenship_front',
            field=models.FileField(blank=True, null=True, upload_to='kyc/citizenship/'),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='citizenship_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='employer_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='grand_father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='income_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='income_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='nominee_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='nominee_dob_ad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='nominee_dob_bs',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='nominee_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='nominee_relation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='occupation_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='office_address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='pan_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='passport_doc',
            field=models.FileField(blank=True, null=True, upload_to='kyc/passport/'),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='perm_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='perm_district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='perm_municipality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='perm_province',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='perm_ward',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='kyc/photos/'),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='kyc/signature/'),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('INCOMPLETE', 'Incomplete')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='temp_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='temp_district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='temp_municipality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='temp_province',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='temp_ward',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='kycform.kycuserinfo'),
        ),
    ]
