# Generated by Django 5.2.8 on 2025-12-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycform', '0009_remove_kycsubmission_bank_account_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycsubmission',
            name='review_comment',
        ),
        migrations.RemoveField(
            model_name='kycsubmission',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='kycsubmission',
            name='reviewed_by',
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='status',
            field=models.CharField(default='INCOMPLETE', max_length=20),
        ),
    ]
