# Generated by Django 5.2.8 on 2025-12-01 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kycform', '0010_remove_kycsubmission_review_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycsubmission',
            name='status',
        ),
    ]
