# Generated by Django 5.2.8 on 2025-12-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycform', '0011_remove_kycsubmission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycsubmission',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='s_lock',
            field=models.BooleanField(default=False),
        ),
    ]
