# Generated by Django 5.2.8 on 2025-12-02 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kycform', '0012_kycsubmission_locked_at_kycsubmission_s_lock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kycsubmission',
            old_name='s_lock',
            new_name='is_lock',
        ),
    ]
