# Generated by Django 5.2.8 on 2025-12-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycform', '0013_rename_s_lock_kycsubmission_is_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycsubmission',
            name='locked_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
