# Generated by Django 5.2.8 on 2025-12-03 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycform', '0014_kycsubmission_locked_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kycsubmission',
            name='currently_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_currently_reviewing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='review_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
