# Generated by Django 5.2.8 on 2025-12-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycform', '0015_kycsubmission_currently_reviewed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycsubmission',
            name='rejection_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
