# Generated by Django 5.2.8 on 2025-12-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycform', '0016_kycsubmission_rejection_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycsubmission',
            name='marital_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
