# Generated by Django 5.2.8 on 2025-12-05 07:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycform', '0017_kycsubmission_marital_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycdocument',
            name='file_path',
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='kyc_docs/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs', to='kycform.kycsubmission'),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='doc_type',
            field=models.CharField(choices=[('PHOTO', 'Photo'), ('CITIZENSHIP_FRONT', 'Citizenship Front'), ('CITIZENSHIP_BACK', 'Citizenship Back'), ('SIGNATURE', 'Signature'), ('PASSPORT', 'Passport Document'), ('NID', 'National Identity Card'), ('ADDITIONAL', 'Additional Document')], max_length=50),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='file_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='kycdocument',
            index=models.Index(fields=['user', 'doc_type', 'is_current'], name='kyc_documen_user_id_b0a9f8_idx'),
        ),
    ]
