# Generated by Django 5.2.8 on 2025-12-31 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kycform', '0006_remove_kycuserinfo_address_and_more'),
        ('kycform', '0018_remove_kycdocument_file_path_kycdocument_file_and_more'),
    ]

    operations = [
    ]
