# Generated by Django 5.2.8 on 2025-12-15 06:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycform', '0019_merge_20251215_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='KycChangeLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(blank=True, max_length=100, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('STATUS', 'Status Change'), ('DOCUMENT', 'Document Change')], max_length=20)),
                ('actor_type', models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin'), ('AGENT', 'Agent'), ('SYSTEM', 'System')], max_length=20)),
                ('actor_identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='kycform.kycsubmission')),
            ],
            options={
                'db_table': 'kyc_change_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
